## Deliverable 3. Create a Travel Itinerary Map.

In [15]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [5]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(30)

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,1,Bintulu,MY,84.61,few clouds,3.1667,113.0333,900 Boutique INN
1,3,Rikitea,PF,77.76,overcast clouds,-23.1203,-134.9692,People ThankYou
2,4,Touros,BR,76.84,overcast clouds,-5.1989,-35.4608,INN NEW HORIZON
3,5,Ternate,ID,83.12,overcast clouds,0.8000,127.4000,Sahid Bela Ternate Hotel
4,6,Byron Bay,AU,78.71,broken clouds,-28.6500,153.6167,Backpackers Inn
5,9,Kavaratti,IN,82.51,scattered clouds,10.5669,72.6420,Hotels in Lakshadweep Islands
6,11,Puerto Ayora,EC,76.55,overcast clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
7,19,Calabozo,VE,89.62,overcast clouds,8.9242,-67.4293,Hotel Giardini
8,23,Neiafu,TO,84.88,broken clouds,-18.6500,-173.9833,Mystic Sands Beachfront Accommodation
9,25,Atuona,PF,79.88,few clouds,-9.8000,-139.0333,Villa Enata
10,28,Vaini,TO,78.96,broken clouds,-21.2000,-175.2000,Keleti Beach Resort
11,29,West Bay,KY,80.67,few clouds,19.3667,-81.4167,Calypso Cove
12,41,Kavieng,PG,84.40,overcast clouds,-2.5744,150.7967,Nusa Island Retreat
13,43,Oistins,BB,78.89,scattered clouds,13.0667,-59.5333,Butterfly Beach Hotel
14,48,Georgetown,MY,84.13,few clouds,5.4112,100.3354,Cititel Penang
15,55,Ladario,BR,76.53,clear sky,-19.0047,-57.6017,Hotel Fazenda 4 cantos
16,57,Hithadhoo,MV,82.81,clear sky,-0.6000,73.0833,Scoop Guest House
17,60,Maceio,BR,78.24,scattered clouds,-9.6658,-35.7353,Hotel Ponta Verde Macei√≥
18,63,Port Blair,IN,84.24,scattered clouds,11.6667,92.7500,"Welcomhotel By ITC Hotels, Bay Island, Port Blair"
19,69,Avarua,CK,77.05,few clouds,-21.2078,-159.7750,Paradise Inn
20,70,Hambantota,LK,80.94,few clouds,6.1241,81.1185,Bungalow 63
21,80,Bambous Virieux,MU,79.21,light rain,-20.3428,57.7575,Casa Tia Villa
22,81,Waw,SS,77.56,broken clouds,7.7029,27.9953,Universal Gab Hotel
23,88,Bandarbeyla,SO,75.69,clear sky,9.4942,50.8122,JABIR HOTEL
24,100,Carnarvon,AU,80.67,scattered clouds,-24.8667,113.6333,Hospitality Carnarvon
25,108,Caravelas,BR,76.57,clear sky,-17.7125,-39.2481,Pousada dos Navegantes
26,112,Mahebourg,MU,79.25,broken clouds,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
27,116,Kalmunai,LK,79.56,overcast clouds,7.4167,81.8167,VS Villa
28,118,Susangerd,IR,78.15,overcast clouds,31.5608,48.1831,ÿØŸÅÿ™ÿ± ÿÆÿØŸÖÿßÿ™ ŸáŸàÿß€å€å Ÿàÿ¨ŸáÿßŸÜ⁄Øÿ±ÿØ€å ŸÜÿ≥€åŸÖ ⁄Øÿ≥ÿ™ÿ± ÿØÿ¥ÿ™ ÿ¢ÿ≤ÿßÿØ⁄ØÿßŸÜ
29,119,Bilma,NE,82.27,clear sky,18.6853,12.9164,Expeditions T√©n√©re voyages

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>country code</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} ¬∞F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [6]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,dissipating=False,max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
vacation_df[vacation_df['Country']=="AU"]

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,6,Byron Bay,AU,78.71,broken clouds,-28.6500,153.6167,Backpackers Inn
24,100,Carnarvon,AU,80.67,scattered clouds,-24.8667,113.6333,Hospitality Carnarvon
31,122,Gold Coast,AU,82.17,scattered clouds,-28.0000,153.4333,Mantra Towers of Chevron Surfers Paradise
64,236,Emerald,AU,80.74,overcast clouds,-23.5333,148.1667,The Irish Village
70,263,Mount Isa,AU,89.37,clear sky,-20.7333,139.5000,ibis Styles Mt Isa Verona
126,478,Mackay,AU,84.69,light rain,-21.1500,149.2000,International Lodge Motel
152,599,Kiama,AU,79.38,broken clouds,-34.6833,150.8667,The Sebel Kiama Harbourside
160,625,Alice Springs,AU,83.75,clear sky,-23.7000,133.8833,Desert Palms Alice Springs

In [35]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[24]
vacation_end = vacation_df.loc[24]
vacation_stop1 = vacation_df.loc[160]
vacation_stop2 = vacation_df.loc[70] 
vacation_stop3 = vacation_df.loc[64]

In [111]:
# tt = pd.DataFrame([],columns=vacation_df.columns)
# tt

Empty DataFrame
Columns: [City_ID, City, Country, Max Temp, Current Description, Lat, Lng, Hotel Name]
Index: []

In [38]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start.to_numpy()[[5,6]]
end = vacation_start.to_numpy()[[5,6]]
stop1 = vacation_stop1.to_numpy()[[5,6]]
stop2 = vacation_stop2.to_numpy()[[5,6]]
stop3 = vacation_stop3.to_numpy()[[5,6]]

In [41]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
driving_map = gmaps.directions_layer(
        start, end, waypoints=[stop1,stop2,stop3],
        travel_mode='DRIVING')
fig.add_layer(driving_map)
fig

Figure(layout=FigureLayout(height='420px'))

In [136]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],axis=1,ignore_index=True).T
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,100,Carnarvon,AU,80.67,scattered clouds,-24.8667,113.6333,Hospitality Carnarvon
1,625,Alice Springs,AU,83.75,clear sky,-23.7,133.8833,Desert Palms Alice Springs
2,263,Mount Isa,AU,89.37,clear sky,-20.7333,139.5,ibis Styles Mt Isa Verona
3,236,Emerald,AU,80.74,overcast clouds,-23.5333,148.1667,The Irish Village

In [140]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>country code</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
itinerary_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[['Lat', 'Lng']]

In [141]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,dissipating=False,max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=itinerary_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))